name: Feature Request
description: Adição de nova funcionalidade
labels: ["feature-request"]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: Describe the requested feature.
    validations:
      required: true